In [1]:
# import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import data_tool as dt
import time

epoch_count = 30

In [2]:
matrix = dt.get_random_binary_signature_matrix(100,50)

In [6]:
Y_set_noise, X_set, H_set, Y_set = dt.get_dataset_with_noise(1000, matrix, 10)

In [9]:
Y_set_noise[0]

array([ -1.54157982,   3.06745986,  -0.09349052,   3.33573807,
        -1.09233301,  -4.03042862,  -0.32095051,   5.01496864,
         5.94717778,  -1.75844619,  -1.58449531,  -6.63289219,
         3.56329394,  -3.79336782,   5.9856853 ,   1.74875733,
        -2.65677798,  -1.91203304,  -1.97133995,  -2.47814513,
        -3.81985846,  -1.566793  ,  -2.14979505,   5.48797762,
        -7.62027703,  -1.3878589 ,   5.57083877,   3.0766069 ,
        -1.12506026,  -0.67454915,   2.41726414,   3.12773072,
         8.43958482,   4.11663364,   1.14600262,  -3.72616291,
         1.78933087,  -0.23310496,  -0.50511797,   5.140689  ,
       -10.09081452,  -7.6618477 ,   5.91356989,  -4.08219128,
        -1.17082618,   1.35033746,   0.90810682,   0.92174839,
        -3.65630467,   0.8695826 ])

In [14]:
np.mean(Y_set - Y_set_noise)

0.0009251185111910144

In [15]:
np.var(Y_set - Y_set_noise)

1.0109375318961582

In [17]:
dt.snr_tool_rate_2_dB(10/1)

10.0

In [3]:
Y_set, _, _ = dt.get_dataset(1000, matrix, acteve_rate = 0.1, is_fading = 0)

In [4]:
Y_set

array([[ 1, -1, -1, ..., -1,  1, -3],
       [ 2, -2,  2, ...,  0, -4, -2],
       [-1,  3,  1, ..., -1,  1, -1],
       ...,
       [-2,  0, -2, ...,  2,  0, -4],
       [-1,  3, -1, ..., -5,  1,  1],
       [ 6,  2, -4, ...,  2, -4, -2]])

In [5]:
np.power(Y_set, 2)

array([[ 1,  1,  1, ...,  1,  1,  9],
       [ 4,  4,  4, ...,  0, 16,  4],
       [ 1,  9,  1, ...,  1,  1,  1],
       ...,
       [ 4,  0,  4, ...,  4,  0, 16],
       [ 1,  9,  1, ..., 25,  1,  1],
       [36,  4, 16, ...,  4, 16,  4]])

In [6]:
y_pow = np.power(Y_set, 2)

In [7]:
(np.sum(y_pow)/1000)/50

10.114840000000001

In [24]:
y_pow[0].sum()/

290

In [30]:
y_pow.sum()/50

10316.88

In [19]:
dt.test_power_of_signature_matrix(matrix, 50, test_data_size=100000)

10.05749

In [28]:
def snr_tool_dB_2_rate(dB):
    return np.power(10., dB/10.)

def snr_tool_rate_2_dB(rate):
    return 10. * np.log10(rate)

In [35]:
snr_tool_dB_2_rate(-3.830763998477274)

0.4139268515822508

In [37]:
snr_tool_rate_2_dB(0.4139268515822508)

-3.830763998477274

In [2]:
import numpy as np

In [75]:
np.count_nonzero(np.random.rayleigh(size=100000000, scale=1)<=0.01)

5039

In [77]:
np.count_nonzero(np.random.rayleigh(size=100000000)<=0.001)

59

In [44]:
def p_of_rayleigh(x, scale=1):
    p = x * np.exp(-pow(x, 2) / (2 * pow(scale, 2)))
    return p / pow(scale, 2)

In [42]:
np.exp(-pow(1,2))

0.36787944117144233

In [43]:
-pow(1,2)/2sc

1

In [69]:
p_of_rayleigh(0.5,scale=1)

0.4412484512922977

In [65]:
4863 / 100000000

4.863e-05

In [78]:
59 / 100000000

5.9e-07

In [79]:
def CDF_of_rayleigh(x, scale=1):
    return 1 - np.exp(-pow(x, 2) / (2 * pow(scale, 2)))

In [84]:
CDF_of_rayleigh(0.001)

4.999998749477541e-07

In [85]:
p_of_rayleigh(0.001,scale=1)

0.000999999500000125