In [1]:
import tensorflow as tf
import numpy as np

In [12]:
print tf.config.list_physical_devices()

[PhysicalDevice(name=u'/physical_device:CPU:0', device_type=u'CPU'), PhysicalDevice(name=u'/physical_device:XLA_CPU:0', device_type=u'XLA_CPU')]


In [3]:
# In the tf.keras.layers package, layers are objects. To construct a layer,
# simply construct the object. Most layers take as a first argument the number
# of output dimensions / channels.
layer = tf.keras.layers.Dense(100)
# The number of input dimensions is often unnecessary, as it can be inferred
# the first time the layer is used, but it can be provided if you want to
# specify it manually, which is useful in some complex models.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [8]:
# To use a layer, simply call it.
layer(tf.ones([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[-5.8868974e-02,  1.2728840e-01,  2.4428999e-01,  7.7858883e-01,
        -2.4122995e-01, -1.6790628e-04,  8.5247427e-02,  8.8042921e-01,
         7.1803391e-02,  4.4572294e-02],
       [-5.8868974e-02,  1.2728840e-01,  2.4428999e-01,  7.7858883e-01,
        -2.4122995e-01, -1.6790628e-04,  8.5247427e-02,  8.8042921e-01,
         7.1803391e-02,  4.4572294e-02],
       [-5.8868974e-02,  1.2728840e-01,  2.4428999e-01,  7.7858883e-01,
        -2.4122995e-01, -1.6790628e-04,  8.5247427e-02,  8.8042921e-01,
         7.1803391e-02,  4.4572294e-02],
       [-5.8868974e-02,  1.2728840e-01,  2.4428999e-01,  7.7858883e-01,
        -2.4122995e-01, -1.6790628e-04,  8.5247427e-02,  8.8042921e-01,
         7.1803391e-02,  4.4572294e-02],
       [-5.8868974e-02,  1.2728840e-01,  2.4428999e-01,  7.7858883e-01,
        -2.4122995e-01, -1.6790628e-04,  8.5247427e-02,  8.8042921e-01,
         7.1803391e-02,  4.4572294e-02],
       [-5.8868974e-02,  

In [5]:
# Layers have many useful methods. For example, you can inspect all variables
# in a layer using `layer.variables` and trainable variables using
# `layer.trainable_variables`. In this case a fully-connected layer
# will have variables for weights and biases.
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.10499978, -0.15327054, -0.3659627 , -0.3088035 ,  0.6200493 ,
         -0.14629489, -0.5772669 , -0.06316423, -0.18953231,  0.4120229 ],
        [ 0.60925394, -0.14610744,  0.3771276 ,  0.41779238, -0.04109728,
         -0.1442182 , -0.11212784,  0.14595258,  0.32681602, -0.41537207],
        [-0.43399906, -0.4763847 , -0.0956611 ,  0.4140826 ,  0.20087665,
         -0.37475973, -0.46844685, -0.17582044, -0.1812656 ,  0.31502855],
        [ 0.61659676,  0.12726873,  0.5579657 , -0.26358923,  0.42949766,
          0.21365345,  0.12714905, -0.39785522, -0.16547602, -0.590908  ],
        [ 0.13439548, -0.29268295, -0.14994851, -0.31688973,  0.4241076 ,
          0.5319074 ,  0.12866658,  0.35344255,  0.22758484,  0.36271578]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [11]:
# The variables are also accessible through nice accessors
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.290924  ,  0.00194383, -0.5822919 ,  0.59741193,  0.34375387,
         -0.20326951,  0.44000143,  0.4003634 ,  0.2840067 , -0.00813252],
        [-0.4717651 ,  0.17340815,  0.44388908, -0.14590299, -0.33761495,
          0.04149687, -0.5360613 , -0.45632327, -0.54251087,  0.42336982],
        [-0.28585115,  0.21117616,  0.6041388 ,  0.20847714,  0.43630618,
          0.30408865, -0.4335485 , -0.4000682 ,  0.39698726,  0.42312533],
        [ 0.19044471, -0.01320267, -0.36482018,  0.17276543, -0.3744069 ,
          0.03196657, -0.60892713,  0.21614254, -0.13220876,  0.2766598 ],
        [ 0.12596506, -0.60204166,  0.22905022,  0.1963861 , -0.532883  ,
          0.47593743,  0.09940636,  0.22139543,  0.36445796,  0.32747167]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [6]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    self.kernel = self.add_weight("kernel",
                                  shape=[int(input_shape[-1]),
                                         self.num_outputs])

  def call(self, input):
    return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)

In [11]:
layer.call()

TypeError: call() takes exactly 2 arguments (1 given)

In [15]:
_ = layer(tf.zeros([10, 5])) # Calling the layer `.builds` it.

In [16]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer/kernel:0']
